# Generated by Django 4.1.2 on 2023-04-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [

    ]
