# Generated by Django 4.1.2 on 2023-04-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_auto_20230401_1545"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="unit_price",
        ),
    ]
